name: Generate Trackers

on:
  schedule:
    - cron: '0 1 * * *'  # 每天1点执行

jobs:
  generate-trackers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Generate Trackers
        run: |
          node scripts/generate_trackers.js 'aria2_best'
          node scripts/generate_trackers.js 'aria2_all'
          node scripts/generate_trackers.js 'aria2_all_udp'
          node scripts/generate_trackers.js 'aria2_all_http'
          node scripts/generate_trackers.js 'aria2_all_https'
          node scripts/generate_trackers.js 'aria2_all_ws'
          node scripts/generate_trackers.js 'aria2_best_ip'
          node scripts/generate_trackers.js 'aria2_all_ip'

      - name: Commit and Push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Generate trackers on $(date +'%Y-%m-%d %T')"
          git push
