name: Generate Trackers

on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Suffix for the trackers'
        required: false

jobs:
  generate-trackers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Debug
        run: echo "Suffix is ${{ github.event.inputs.suffix || 'best' }}"

      - name: Execute Script
        run: npm run generate-trackers
        env:
          SUFFIX: ${{ github.event.inputs.suffix || 'best' }}
